# Teleop configuration for PS3 Navigation joystick.
bluetooth_teleop:
  teleop_twist_joy:
    axis_linear:
      x: 1
      y: 0
    scale_linear:
      x: 0.4
      y: 0.4
    enable_button: 8
    enable_turbo_button: 10
  joy_node:
    deadzone: 0.1
    autorepeat_rate: 20
